<?php

/**
 * @file
 * This will beautify the text inside the HTML code editor
 */

/**
 * Implements hook_wysiwyg_plugin().
 */
function prettydiff_wysiwyg_plugin($editor, $version) {

	// To get this fully working, the tinymce-prettydiff plugin must be added
	// to the tiny mce plugins directory
	// So far, it only supports v3.

	if ($editor === 'tinymce'){

		return array(
			'prettydiff' => array(
				'path' => wysiwyg_get_path('tinymce') . '/jscripts/tiny_mce/plugins/prettydiff',
				'filename' => 'editor_plugin.js',
				'buttons' => array('prettydiff' => t('PrettyDiff Code Beautifier (Must have "Source Code" also selected)')),
				'url' => 'http://www.websiteconnect.com.au/',
				'internal' => false,
				'load' => true,
			),
		);
	}

	return array();

}